import Link from 'next/link';
import {ArrowRight, CalendarDays, Check, Clock3, Scissors, Sparkles, Star, UsersRound} from 'lucide-react';
import {PublicLayout} from '@/components/PublicLayout';
import {services,haircutCatalog} from '@/lib/demo-data';

const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function Home(){return <PublicLayout><main>
  <section className="hero hero-premium"><div className="hero-photo" aria-hidden="true"/><div className="hero-overlay"/><div className="container hero-content"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot"/> Fiapos Barbershop • Nova Iguaçu</span><h1>Seu corte.<br/><em>Sua presença.</em></h1><p>Uma experiência de barbearia feita para quem valoriza estilo, cuidado e tempo. Escolha seus serviços e reserve seu horário em poucos passos.</p><div className="hero-actions"><Link className="btn btn-primary btn-lg" href="/agendar"><CalendarDays size={19}/> Agendar agora</Link><Link className="btn btn-glass btn-lg" href="/servicos">Conhecer serviços <ArrowRight size={18}/></Link></div><div className="hero-proof"><span><Check size={15}/> Agendamento online</span><span><Check size={15}/> Atendimento com hora marcada</span><span><Check size={15}/> Nova Iguaçu - RJ</span></div></div><div className="floating-booking"><div className="booking-mini-top"><span>Seu próximo horário</span><span className="status-dot">Online</span></div><div className="booking-mini-date"><CalendarDays/><div><small>Reserve em poucos passos</small><strong>Serviço → profissional → horário</strong></div></div><div className="booking-mini-row"><span><Clock3 size={16}/> duração calculada</span><span><Scissors size={16}/> vários serviços</span></div><Link href="/agendar" className="btn btn-primary btn-block">Escolher serviços <ArrowRight size={17}/></Link></div></div></section>

  <section className="trust-strip"><div className="container trust-grid"><div><strong>+20</strong><span>anos de tradição</span></div><div><strong>100%</strong><span>fluxo online</span></div><div><strong>1</strong><span>reserva, vários serviços</span></div><div><strong>Mobile</strong><span>feito para o celular</span></div></div></section>

  <section className="section section-light"><div className="container"><div className="section-head"><div><span className="eyebrow dark">Serviços</span><h2>Escolha o cuidado que combina com você.</h2></div><Link className="text-link" href="/servicos">Ver catálogo completo <ArrowRight size={17}/></Link></div><div className="service-grid">{services.slice(0,6).map((s,index)=><article className="service-card" key={s.id}><div className="service-card-top"><span className="service-number">0{index+1}</span><span className="service-category">{s.category}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="service-meta"><span><Clock3 size={16}/>{s.duration} min</span><strong>{money(s.price)}</strong></div><Link className="service-action" href={`/agendar?service=${s.id}`}>Adicionar e agendar <ArrowRight size={16}/></Link></article>)}</div></div></section>

  <section className="experience-section"><div className="container experience-grid"><div className="experience-image"><div className="experience-badge"><Star size={17} fill="currentColor"/><span><strong>Experiência Fiapos</strong><small>do atendimento ao acabamento</small></span></div></div><div className="experience-copy"><span className="eyebrow">Mais que um corte</span><h2>Uma experiência simples, bonita e sem enrolação.</h2><p>O agendamento foi pensado com padrões de plataformas modernas de serviços: menos etapas desnecessárias, preço e duração sempre visíveis e um resumo que acompanha sua escolha.</p><div className="feature-list"><div><span><Scissors/></span><div><strong>Monte seu atendimento</strong><p>Selecione corte, barba, sobrancelha, tratamento e o que mais quiser em uma única reserva.</p></div></div><div><span><UsersRound/></span><div><strong>Profissional compatível</strong><p>O sistema mostra apenas profissionais que realizam todos os serviços escolhidos.</p></div></div><div><span><Sparkles/></span><div><strong>Horário sem conflito</strong><p>A disponibilidade considera a duração total da sua seleção.</p></div></div></div><Link className="btn btn-outline-light" href="/agendar">Começar agendamento <ArrowRight size={17}/></Link></div></div></section>

  <section className="section section-dark-alt"><div className="container"><div className="section-head inverted"><div><span className="eyebrow">Inspire-se</span><h2>Referências para o seu próximo visual.</h2></div><Link className="text-link light" href="/cortes">Ver todos <ArrowRight size={17}/></Link></div><div className="look-grid">{haircutCatalog.map((c,i)=><article className={`look-card look-${i+1}`} key={c.id}><div className="look-shade"/><div className="look-content"><span>{c.category}</span><h3>{c.name}</h3><p>{c.description}</p><Link href={`/agendar?haircut=${c.id}`} className="look-link">Quero esse corte <ArrowRight size={16}/></Link></div></article>)}</div></div></section>

  <section className="section section-light"><div className="container"><div className="booking-cta"><div><span className="eyebrow dark">Pronto para mudar o visual?</span><h2>Escolha os serviços. A Fiapos cuida do resto.</h2><p>Você vê preço, duração, profissional e horários disponíveis antes de confirmar.</p></div><Link href="/agendar" className="btn btn-primary btn-lg">Agendar meu horário <ArrowRight size={18}/></Link></div></div></section>
</main></PublicLayout>}
