'use client';
import {useMemo,useState} from 'react';
import {CalendarPlus,CheckCircle2,Filter,Search,Trash2,XCircle} from 'lucide-react';
import {useAdminStore} from './useAdminStore';
import type {AdminAppointment,AppointmentStatus} from '@/lib/admin-store';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels:Record<AppointmentStatus,string>={pending:'Pendente',confirmed:'Confirmado',completed:'Concluído',cancelled:'Cancelado'};

export function AdminAppointments(){
 const {appointments,employees,setAppointments}=useAdminStore(); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|AppointmentStatus>('all'); const [show,setShow]=useState(false);
 const [form,setForm]=useState({customer:'',phone:'',service:'Corte Masculino',barberId:'',date:new Date().toISOString().slice(0,10),time:'09:00',duration:40,total:45});
 const visible=useMemo(()=>appointments.filter(a=>(filter==='all'||a.status===filter)&&(`${a.customer} ${a.phone} ${a.serviceNames.join(' ')}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)),[appointments,filter,query]);
 function status(id:string,status:AppointmentStatus){setAppointments(appointments.map(a=>a.id===id?{...a,status}:a))}
 function create(){const employee=employees.find(e=>e.id===form.barberId)||employees.find(e=>e.active);if(!form.customer||!employee)return;const item:AdminAppointment={id:`apt-${Date.now()}`,customer:form.customer,phone:form.phone,serviceNames:[form.service],barberId:employee.id,barberName:employee.name,date:form.date,time:form.time,duration:Number(form.duration),total:Number(form.total),status:'confirmed',createdAt:new Date().toISOString()};setAppointments([item,...appointments]);setShow(false);setForm({...form,customer:'',phone:''})}
 return <>
  <div className="admin-heading"><div><span className="eyebrow dark">Operação</span><h1>Agendamentos</h1><p>Confirme, conclua, cancele e crie reservas pela administração.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><CalendarPlus size={17}/> Novo agendamento</button></div>
  <div className="admin-toolbar"><label className="admin-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, telefone ou serviço"/></label><label className="admin-filter"><Filter size={15}/><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">Todos os status</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
  <section className="admin-card admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Cliente</th><th>Serviços</th><th>Profissional</th><th>Data</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><strong>{a.customer}</strong><small>{a.phone}</small></td><td><strong>{a.serviceNames.join(' + ')}</strong><small>{a.duration} min</small></td><td>{a.barberName}</td><td><strong>{a.date.split('-').reverse().join('/')}</strong><small>{a.time}</small></td><td>{money(a.total)}</td><td><span className={`status-badge ${a.status}`}>{labels[a.status]}</span></td><td><div className="table-actions">{a.status==='pending'&&<button title="Confirmar" onClick={()=>status(a.id,'confirmed')}><CheckCircle2/></button>}{a.status==='confirmed'&&<button title="Concluir" onClick={()=>status(a.id,'completed')}><CheckCircle2/></button>}{a.status!=='cancelled'&&a.status!=='completed'&&<button title="Cancelar" onClick={()=>status(a.id,'cancelled')}><XCircle/></button>}<button title="Excluir" onClick={()=>setAppointments(appointments.filter(x=>x.id!==a.id))}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>
  {show&&<div className="admin-modal-backdrop" onMouseDown={()=>setShow(false)}><div className="admin-modal" onMouseDown={e=>e.stopPropagation()}><div className="admin-card-head"><div><small>NOVA RESERVA</small><h2>Criar agendamento</h2></div><button className="icon-button" onClick={()=>setShow(false)}>×</button></div><div className="admin-form-grid"><label><span>Cliente</span><input value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label><span>WhatsApp</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span>Serviço</span><input value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/></label><label><span>Profissional</span><select value={form.barberId} onChange={e=>setForm({...form,barberId:e.target.value})}><option value="">Primeiro ativo</option>{employees.filter(e=>e.active).map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label><span>Data</span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label><span>Horário</span><input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label><span>Duração (min)</span><input type="number" value={form.duration} onChange={e=>setForm({...form,duration:Number(e.target.value)})}/></label><label><span>Valor (R$)</span><input type="number" value={form.total} onChange={e=>setForm({...form,total:Number(e.target.value)})}/></label></div><button className="btn btn-primary btn-block" onClick={create}>Salvar agendamento</button></div></div>}
 </>
}